language: clojure
script:
  - lein cljsbuild once min
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  local_dir: resources/public
  target_branch: gh-pages
  on:
    branch: master
